packages:
  # all packages in subdirs of packages/ and components/
  - "finance-backend/**"
  - "finance-frontend/**"
  - "components/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
