import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { FeaturesTitle } from "../components/features";
import { FooterSimple } from "../components/footer";
import { HeroText } from "../components/hero";
import { HeaderMiddle } from "../components/navBar";
import styles from "../styles/Home.module.css";

const headerLinks = [
  {
    link: "overview",
    label: "Overview",
  },
  {
    link: "features",
    label: "Features",
  },
];

const footerLinks = [
  {
    link: "about",
    label: "About",
  },
  {
    link: "team",
    label: "Team",
  },
  {
    link: "contact",
    label: "Contact",
  },
];

const Home: NextPage = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Finance</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeaderMiddle links={headerLinks} />
        <HeroText />
        <FeaturesTitle />
        <FooterSimple links={footerLinks} />
      </div>
    </>
  );
};

export default Home;
