import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { FeaturesGrid } from "../components/features";
import { HeroText } from "../components/hero";
import { HeaderAction } from "../components/navBar";
import styles from "../styles/Home.module.css";

const links = [
  {
    link: "TestLink",
    label: "Overview",
  },
  {
    link: "TestLink1",
    label: "Banks",
    links: [
      { link: "TestSubLink1", label: "BPI" },
      { link: "TestSubLink1", label: "BDO" },
      { link: "TestSubLink1", label: "AFP" },
    ],
  },
  {
    link: "TestLink1",
    label: "Crypto",
    links: [
      { link: "TestSubLink1", label: "BTC" },
      { link: "TestSubLink1", label: "ETH" },
      { link: "TestSubLink1", label: "DOT" },
      { link: "TestSubLink1", label: "ALGO" },
      { link: "TestSubLink1", label: "AXS" },
      { link: "TestSubLink1", label: "ADA" },
    ],
  },
];
const Home: NextPage = () => {
  return (
    <>
      <HeaderAction links={links} />
      <HeroText />
      <FeaturesGrid
        title={"FINACHEE"}
        description={"FINANCEE GOT U BROOOO DW"}
      />
      <div className={styles.container}>
        <Head>
          <title>Finance</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
    </>
  );
};

export default Home;
