// Generates iOS PWA splash screens + the matching Next metadata entries.
// iOS ignores manifest splash fields; it needs per-device
// `apple-touch-startup-image` links. Regen: `pnpm --filter @funds/web splash`.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const iconPath = join(root, "public", "icons", "icon-512.png");
const outDir = join(root, "public", "splash");
const outTs = join(root, "src", "generated", "pwa-splash.ts");

// Physical pixels (portrait), device pixel ratio, and which orientations to ship.
// iPhones launch portrait; iPads need both.
const DEVICES = [
  { w: 750, h: 1334, ratio: 2, landscape: false }, // SE 2/3
  { w: 828, h: 1792, ratio: 2, landscape: false }, // 11 / XR
  { w: 1125, h: 2436, ratio: 3, landscape: false }, // X / XS / 11 Pro
  { w: 1170, h: 2532, ratio: 3, landscape: false }, // 12 / 13 / 14
  { w: 1179, h: 2556, ratio: 3, landscape: false }, // 14 Pro / 15 / 16
  { w: 1206, h: 2622, ratio: 3, landscape: false }, // 16 Pro
  { w: 1242, h: 2688, ratio: 3, landscape: false }, // XS Max / 11 Pro Max
  { w: 1284, h: 2778, ratio: 3, landscape: false }, // Plus / older Pro Max
  { w: 1290, h: 2796, ratio: 3, landscape: false }, // 14-15 Pro Max
  { w: 1320, h: 2868, ratio: 3, landscape: false }, // 16 Pro Max
  { w: 1488, h: 2266, ratio: 2, landscape: true }, // iPad mini 6
  { w: 1536, h: 2048, ratio: 2, landscape: true }, // iPad 9.7"
  { w: 1620, h: 2160, ratio: 2, landscape: true }, // iPad 10.9"
  { w: 1640, h: 2360, ratio: 2, landscape: true }, // iPad Air
  { w: 1668, h: 2388, ratio: 2, landscape: true }, // iPad Pro 11" (older)
  { w: 1668, h: 2420, ratio: 2, landscape: true }, // iPad Pro 11" / Air 11"
  { w: 2048, h: 2732, ratio: 2, landscape: true }, // iPad Pro 12.9"
];

const media = (cw, ch, ratio, orientation) =>
  `(device-width: ${cw}px) and (device-height: ${ch}px) and (-webkit-device-pixel-ratio: ${ratio}) and (orientation: ${orientation})`;

const bg = await sharp(iconPath)
  .extract({ left: 0, top: 0, width: 1, height: 1 })
  .raw()
  .toBuffer()
  .then((b) => ({ r: b[0], g: b[1], b: b[2] }));

mkdirSync(outDir, { recursive: true });
mkdirSync(dirname(outTs), { recursive: true });

const entries = [];
for (const d of DEVICES) {
  const orientations = d.landscape ? ["portrait", "landscape"] : ["portrait"];
  for (const o of orientations) {
    const W = o === "portrait" ? d.w : d.h;
    const H = o === "portrait" ? d.h : d.w;
    const file = `apple-splash-${W}-${H}.png`;
    const mark = await sharp(iconPath)
      .resize({ width: Math.round(W * 0.5) })
      .png()
      .toBuffer();
    await sharp({ create: { width: W, height: H, channels: 3, background: bg } })
      .composite([{ input: mark, gravity: "center" }])
      .png({ compressionLevel: 9 })
      .toFile(join(outDir, file));
    entries.push({
      url: `/splash/${file}`,
      media: media(
        (o === "portrait" ? d.w : d.h) / d.ratio,
        (o === "portrait" ? d.h : d.w) / d.ratio,
        d.ratio,
        o,
      ),
    });
    console.log(file);
  }
}

writeFileSync(
  outTs,
  `// Generated by scripts/generate-splash.mjs — do not edit. Regen: pnpm splash.\n` +
    `export const SPLASH_STARTUP_IMAGES: { url: string; media: string }[] = ${JSON.stringify(entries, null, 2)};\n`,
);
console.log(`Wrote ${entries.length} entries to src/generated/pwa-splash.ts`);
