import type { NextPage } from 'next'
import Head from 'next/head'
import { ActionIcon, Container, Group } from '@mantine/core'
import CreateForm from "../components/CreateForm"
import TransactionList from '../components/TransactionList'
import { IconFilter, IconSettings } from '@tabler/icons'

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Financhi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container sx={{ marginTop: "50px", display: "flex", flexDirection: "column" }}>
        <Group position="apart">
          <Group>
            <ActionIcon>
              <IconSettings />
            </ActionIcon>
            <ActionIcon>
              <IconFilter />
            </ActionIcon>

          </Group>

          <CreateForm />
        </Group>
        <TransactionList />
      </Container>
    </>
  )
}

export default Home
