import { Anchor, Box, Button, Container, Grid, Table, Text } from '@mantine/core'
import { BsChevronDoubleRight } from 'react-icons/bs'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link';


const banks = [
  {
    name: 'BPI',
    balance: 100,
    color: 'red',
    textColor: 'white',
  },
  {
    name: 'CIMB',
    balance: 200,
    color: 'red',
    textColor: 'white',
  },
  {
    name: 'BDO',
    balance: 300,
    color: 'purple',
    textColor: '#ffffff',
  },
  {
    name: 'AFPSLAI Capital',
    balance: 100,
    color: 'green',
    textColor: '#ffffff',
  },
  {
    name: 'AFPSLAI Savings',
    balance: 200,
    color: 'green',
    textColor: '#ffffff',
  },
  {
    name: 'CASH',
    balance: 300,
    color: 'limegreen',
    textColor: '#ffffff',
  },
];

type StatItemProps = {
  name: string,
  color: string,
  textColor: string,
  balance: number,
}

const StatItem = (props: StatItemProps) => {
  const { name, color, textColor, balance } = props;
  return (
    <>
      <Grid.Col span={2} >
        <Container
          sx={{
            backgroundColor: color,
            boxShadow: `5px 5px 5px 0px rgba(255,255,255,0.15)`,
            height: "75px",
            borderRadius: 10,
            padding: "10px",
            maxWidth: "200px",
            minWidth: "130px",
            // overflowWrap: "anywhere",
          }}>
          <Text
            size={'sm'}
            weight={'bolder'}
            color={textColor}
          >
            {name}
          </Text>

          <Text
            size='lg'
            weight="normal"
            color={textColor}>
            {`${balance.toLocaleString(undefined, { style: "currency", currency: "PHP", maximumFractionDigits: 2 })}`}
          </Text>
        </Container>
      </Grid.Col>
    </>
  )
};

const TableHeaders = () => {
  return (
    <>
      <tr>
        <th>Date</th>
        <th>Description</th>
        <th>Bank</th>
        <th>Balance</th>
      </tr>
    </>
  )
}

const fakeTableData = [
  {
    date: '2020-01-01',
    description: 'Initial Deposit',
    bank: 'BPI',
    balance: 100,

  },
  {
    date: '2020-01-02',
    description: 'Bought Shit',
    bank: 'BPI',
    balance: -100,
  },
  {
    date: '2020-01-02',
    description: 'Bought Shit',
    bank: 'BPI',
    balance: -100,
  },
  {
    date: '2020-01-02',
    description: 'Sold Shit',
    bank: 'BDO',
    balance: -100,
  },
  {
    date: '2020-01-02',
    description: 'Made Shit',
    bank: 'BPI',
    balance: -100,
  },
  {
    date: '2020-01-02',
    description: 'Burned Shit',
    bank: 'BPI',
    balance: -100,
  },
  {
    date: '2020-01-02',
    description: 'Burned Shit',
    bank: 'BPI',
    balance: -100,
  },
]

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Financhi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container sx={{ marginTop: "50px" }}>
        <Box
          sx={{
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center"
          }}
        >
          <Text
            weight={"bolder"}
            sx={{
              fontSize: "30px"
            }}
          >
            Bank Balances
          </Text>
          <Link href="#z" passHref>
            <Button
              variant='outline'
              component='a'
              sx={{ height: "25px" }}
              rightIcon={<BsChevronDoubleRight />}
            >
              Bank Actions
            </Button>
          </Link>

        </Box>


        <Grid grow>
          {banks.map((bank, index) => {
            return <StatItem key={index} {...bank} />
          })}
        </Grid>
        <Text weight={"bolder"} size="lg" sx={{ marginTop: "20px" }}>Latest Transactions</Text>
        <Table striped highlightOnHover captionSide='bottom' >
          <thead><TableHeaders /></thead>
          <tbody>
            {fakeTableData.map((data, index) => {
              return (
                <tr key={index}>
                  <td>{data.date}</td>
                  <td>{data.description}</td>
                  <td>{data.bank}</td>
                  <td>{data.balance.toLocaleString(undefined, { style: "currency", currency: "PHP", maximumFractionDigits: 2 })}</td>
                </tr>)
            })}
          </tbody>
          <caption>Seven (7) latest recorded transactions.</caption>
        </Table>
      </Container>

    </>
  )
}

export default Home
