import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { ActionIcon, Container, Group } from "@mantine/core";
import Create from "../components/Create";
import TransactionList from "../components/TransactionList";
import { IconFilter, IconSettings } from "@tabler/icons";
import { BankStats } from "../components/BankStats";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Financhi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        sx={{
          marginTop: 20,
          display: "flex",
          flexDirection: "column",
          "@media screen and (display-mode: standalone)": {
            paddingTop: "80px",
          },
        }}
      >
        <BankStats />
        <Group position="apart">
          <Group>
            <ActionIcon disabled>
              <IconSettings />
            </ActionIcon>
            <ActionIcon disabled>
              <IconFilter />
            </ActionIcon>
          </Group>
          <Create />
        </Group>
        <TransactionList />
      </Container>
    </>
  );
};

export default Home;
