import type { NextPage } from "next";
import Head from "next/head";
//import styles from "../styles/Home.module.css";
import { NavbarMinimalColored } from "../../components/dashboard/Navigation";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dashboard | Finance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarMinimalColored />
    </>
  );
};

export default Home;
